### ISSUE TITLE
v2.properties

### ISSUE THREAD

**Issue by ligi** [KeystoneHQ/Keystone-cold-app#105]
The readme states here: https://github.com/KeystoneHQ/Keystone-cold-app#build
that one can build the app via `./gradlew assembleVault_v2Release`

when doing this I get: 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/ligi/git/3rd/Keystone-cold-app/app/build.gradle' line: 265

* What went wrong:
A problem occurred evaluating project ':app'.
> could not find /home/ligi/git/3rd/Keystone-cold-app/keystores/v2.properties

```

seems there are release keystore definitions in there and I can work around it. But it would be better if a debug build would not fail for this.

**Comment by aaronisme** [comment]
Thanks, @ligi I think we do need to add a debug build for this

**Comment by aaronisme** [comment]
Moved this issue to our development board, close this for now
