### ISSUE TITLE
Please use a gpg key to sign releases and commits

### ISSUE THREAD

**Issue by jonathancross** [KeystoneHQ/Keystone-cold-app#131]
* Releases should have an ascii-armored gpg `.sig` file for each item in the release. (or a single, clear-signed text file containing a list of sha256 checksums of all binaries)
* Ideally, each commit should also be signed for auditability.

Why: so we know the release / commit was actually made by someone other than a rogue GitHub employee, malware / hacker with account credentials or attacker who can break TLS, etc.

**Comment by aaronisme** [comment]
@jonathancross Currently the firmware was signed by one private key by Keystone Team. The firmware will verify the signature when upgrading.

**Comment by jonathancross** [comment]
Thanks @aaronisme , but I'm a bit unclear.

I still don't see GPG signatures for this app.
Neither for the source releases [1] nor for the apk on your website [2].

[1] https://github.com/KeystoneHQ/Keystone-cold-app/releases

[2] https://keyst.one/contents/KeystoneMobile/Keystone_V1.1.1.apk

RE: firmware...

That is also important, but a separate issue.

Are you saying the firmware is signed with a gpg signature and that GPG signature is verified in the device before upgrades? Using GPG here would be unusual, but interesting.

Note: I'm specifically referring to "GPG" (technically OpenPGP standard) because it is much more robust than 
a simple _"an RSA signature"_. The OpenPGP web of trust allows users to verify the _*authenticity*_ of the signing key rather than trusting infrastructure.

**Comment by aaronisme** [comment]
@jonathancross what I mean is the firmware we published is signed by an RSA PrivateKey. And The firmware will check the signature when doing the upgrade. You can check out more detail about it here: https://github.com/KeystoneHQ/Keystone-developer-hub/blob/main/application/Keystone_Application_Update_Package_Verification.md. 

I think I probably misunderstand your suggestion, I think we mean to use a gpg key to create and sign the GitHub release ?

**Comment by jonathancross** [comment]
> use a gpg key to create and sign the GitHub release ?

Yes. Exactly.
