### ISSUE TITLE
I think I bricked my wallet.

### ISSUE THREAD

**Issue by Welved** [KeystoneHQ/Keystone-cold-app#473]
The device has no issues formatting the micoSD, it has an issue with reading. In the mission to downgrade back down to 12.0 (multi), I downloaded and installed bitcoin only to downgrade to 12.0 (multi).

How do I actually wipe this thing? It looks like, as far as wiping goes... it doesn't actually wipe the device to start. It still retains the installed version.

**Comment by soralit** [comment]
Hi @Welved , the btc-only version is not compatible with mutli-coin so once you switch you Keystone to btc-only you will not able to go back. You can contact our customer service for more info. Just visit our website: https://keyst.one/ and click the chat icon at right bottom corner.

**Comment by Welved** [comment]
Yea... my keystone is now a paper weight. There is no way to get a refund nor a way to factory reset the keystone. Keystone the company, basically said "fuck you".
